// homepage/src/examples/infinite-scroll/angular/infinite-scroll.ts
import '@angular/compiler';
import { CommonModule } from '@angular/common';
import { Component, signal, computed } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import LayoutVirtual from 'angular-layout-virtual';

const SHOW_LOADER = Symbol('show-loader');
type Post = { title: string; body: string } | typeof SHOW_LOADER;

@Component({
  selector: '#app',
  standalone: true,
  imports: [CommonModule, LayoutVirtual],
  template: `
    <h4>Try resizing the container and scroll.</h4>
    <div>
      Rendered indices {{ startIndex() }} - {{ endIndex() }}, total {{ total() }}.
      Loaded {{ data().length }} of {{ dataLimit() }}.
    </div>
    <layout-virtual
      [overscanHeight]="200"
      [data]="listData()"
      scrollerClass="lv-scroller"
      viewportClass="lv-viewport"
      contentLayerClass="lv-content-layer"
      (afterItemsRendered)="onAfterRender(...$event)">
        <ng-template #renderItem let-itemData="data" let-index="index">
          @if (itemData===loader) {
            <div class="loader-container" [attr.data-index]="index">
              <div class="loader"></div>
            </div>
          } @else {
            <div class="article-card" [attr.data-index]="index">
              <span class="ac-index">{{ index }}</span>
              <h3 class="ac-title">{{ itemData.title }}</h3>
              <p class="ac-body">{{ itemData.body }}</p>
              <button class="ac-button">Learn more</button>
            </div>
          }
        </ng-template>
    </layout-virtual>
  `,
})
export default class InfiniteScrollExample {
  private loadedUrls = new Set<string>();

  data = signal<Post[]>([]);
  dataLimit = signal(100);
  isLoading = signal(false);
  loader = SHOW_LOADER;

  listData = computed(() =>
    this.isLoading() ? this.data().concat(SHOW_LOADER) : this.data()
  );

  startIndex = signal(0);
  endIndex = signal(0);
  total = computed(() => this.endIndex() - this.startIndex() + 1);

  onAfterRender(start: number, end: number, _:  unknown) {
    console.log('onAfterItemsRendered', start, end);
    if (end === this.data().length - 1 && end < this.dataLimit() - 1 && !this.isLoading()) {
      console.log('will try to fetch data');
      this.loadMore(10, this.data().length);
    }
    this.startIndex.set(start);
    this.endIndex.set(end);
  }

  private loadMore(limit: number, skip: number) {
    const apiUrl = `https://dummyjson.com/posts?limit=${limit}&skip=${skip}&select=title,body`;
    if (this.loadedUrls.has(apiUrl)) return;

    this.isLoading.set(true);
    this.loadedUrls.add(apiUrl);
    console.log('will fetch', apiUrl);

    fetch(apiUrl)
      .then(result => result.json())
      .then(result => {
        this.dataLimit.set(result.total);
        this.data.update(posts => posts.concat(result.posts));
      })
      .catch(console.error)
      .finally(() => this.isLoading.set(false));
  }
}

bootstrapApplication(InfiniteScrollExample).catch((error: unknown) => {
  console.error(error);
});

// homepage/src/examples/infinite-scroll/vue/infinite-scroll.vue
<script setup lang="ts" generic="T">
import { ref, computed, shallowRef } from 'vue';
import LayoutVirtual from 'vue-layout-virtual';
import type { VirtualizedListVueClasses } from 'vue-layout-virtual';

const styling: VirtualizedListVueClasses = {
  scrollerClass: 'lv-scroller',
  viewportClass: 'lv-viewport',
  contentLayerClass: 'lv-content-layer',
};

const SHOW_LOADER = Symbol('show-loader');
type Post = { title: string; body: string } | typeof SHOW_LOADER;

const loadedUrls = shallowRef(new Set<string>());
const data = ref<Post[]>([]);
const dataLimit = ref(100);
const isLoading = ref(false);

const listData = computed(() =>
  isLoading.value ? data.value.concat(SHOW_LOADER) : data.value
);

const startIndex = ref(0);
const endIndex = ref(0);
const total = computed(() => endIndex.value - startIndex.value + 1);

function loadMore(limit: number, skip: number) {
  const apiUrl = `https://dummyjson.com/posts?limit=${limit}&skip=${skip}&select=title,body`;
  if (loadedUrls.value.has(apiUrl)) return;

  isLoading.value = true;
  loadedUrls.value.add(apiUrl);
  console.log('will fetch', apiUrl);

  fetch(apiUrl)
    .then(response => response.json())
    .then(result => {
      dataLimit.value = result.total;
      data.value = data.value.concat(result.posts);
    })
    .catch(console.error)
    .finally(() => { isLoading.value = false; });
}

function onAfterRender(start: number, end: number) {
  console.log('onAfterItemsRendered', start, end);
  if (end === data.value.length - 1 && end < dataLimit.value - 1 && !isLoading.value) {
    console.log('will try to fetch data');
    loadMore(10, data.value.length);
  }
  startIndex.value = start;
  endIndex.value = end;
}
</script>

<template>
  <h4>Try resizing the container and scroll.</h4>
  <div>
    Rendered indices {{ startIndex }} - {{ endIndex }}, total {{ total }}.
    Loaded {{ data.length }} of {{ dataLimit }}.
  </div>
  <layout-virtual :overscan-height="200" :data="listData" v-bind="styling" @after-items-rendered="onAfterRender">
    <template #renderItem="{ data: itemData, index }">
      <div v-if="itemData === SHOW_LOADER" class="loader-container" :data-index="index">
        <div class="loader" />
      </div>
      <div v-else class="article-card" :data-index="index">
        <span class="ac-index">{{ index }}</span>
        <h3 class="ac-title">{{ (itemData as { title: string; body: string }).title }}</h3>
        <p class="ac-body">{{ (itemData as { title: string; body: string }).body }}</p>
        <button class="ac-button">Learn more</button>
      </div>
    </template>
  </layout-virtual>
</template>
